.. meta::
   :robots: noindex, nosnippet


.. contents:: On this page
   :local:
   :backlinks: none
   :depth: 2
   :class: singlecol



Interface SyncSession.ErrorHandler
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler:



io.realm.mongodb.sync
=====================



**Enclosing class:**

:ref:`SyncSession <io_realm_mongodb_sync_SyncSession>` 



Interface used to report any session errors.


.. seealso::


   
   - :ref:`SyncConfiguration.Builder.errorHandler(ErrorHandler) <io_realm_mongodb_sync_SyncConfiguration_Builder_errorHandler_ErrorHandler_>` 
      
      
      
   
   
   



Method Summary
==============

.. list-table::
   :header-rows: 1
   
   * - Modifier and Type
     - Method and Description
   
   * - public **void**
     - | :ref:`onError <io_realm_mongodb_sync_SyncSession_ErrorHandler_onError>` (
       |  :ref:`SyncSession <io_realm_mongodb_sync_SyncSession>`  session, 
       |  :ref:`AppException <io_realm_mongodb_AppException>`  error
       | )
       
       
       Callback for errors on a session object.
       
       
       
   
   


Method Detail
=============

.. _onError:

.. _onError__:

.. _ErrorHandler_onError:

.. _ErrorHandler_onError__:

.. _SyncSession_ErrorHandler_onError:

.. _SyncSession_ErrorHandler_onError__:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError__:



onError
-------

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession_io_realm_mongodb_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession__io_realm_mongodb_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession__AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_SyncSession_io_realm_mongodb_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_SyncSession__io_realm_mongodb_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_SyncSession_AppException_:

.. _io_realm_mongodb_sync_SyncSession_ErrorHandler_onError_SyncSession__AppException_:

.. _onError_io_realm_mongodb_sync_SyncSession_io_realm_mongodb_AppException_:

.. _onError_io_realm_mongodb_sync_SyncSession__io_realm_mongodb_AppException_:

.. _onError_io_realm_mongodb_sync_SyncSession_AppException_:

.. _onError_io_realm_mongodb_sync_SyncSession__AppException_:

.. _onError_SyncSession_io_realm_mongodb_AppException_:

.. _onError_SyncSession__io_realm_mongodb_AppException_:

.. _onError_SyncSession_AppException_:

.. _onError_SyncSession__AppException_:

.. _SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession_io_realm_mongodb_AppException_:

.. _SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession__io_realm_mongodb_AppException_:

.. _SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession_AppException_:

.. _SyncSession_ErrorHandler_onError_io_realm_mongodb_sync_SyncSession__AppException_:

.. _SyncSession_ErrorHandler_onError_SyncSession_io_realm_mongodb_AppException_:

.. _SyncSession_ErrorHandler_onError_SyncSession__io_realm_mongodb_AppException_:

.. _SyncSession_ErrorHandler_onError_SyncSession_AppException_:

.. _SyncSession_ErrorHandler_onError_SyncSession__AppException_:

.. list-table::
   :header-rows: 1
   
   * - | public **void** :ref:`onError <io_realm_mongodb_sync_SyncSession_ErrorHandler_onError>` (
       |  :ref:`SyncSession <io_realm_mongodb_sync_SyncSession>`  session, 
       |  :ref:`AppException <io_realm_mongodb_AppException>`  error
       | )
       
       
       
   
   * - Callback for errors on a session object. It is not allowed to throw an exception inside an error handler. If the operations in an error handler can throw, it is safer to catch any exception in the error handler. When an exception is thrown in the error handler, the occurrence will be logged and the exception will be ignored.
       
       
       
       
       **Parameters**
       
       - ``session`` - :ref:`SyncSession <io_realm_mongodb_sync_SyncSession>`  this error happened on.
          
          
          
          
          
       - ``error`` - type of error.
          
          
          
       
       
       
       
       
       
       
       
       
   
   



